astring = input()
anewstring = astring.replace("!", "")
anewstring = anewstring.replace("?", "")
anewstring = anewstring.replace(".", "")
anewstring = anewstring.replace(",", "")
print(anewstring.lower())
